version: '3.7'
services:
  anonymizer:
    image: intersystems/demo/irishealth/csv-anonymizer:latest
    init: true
    build:
      context: .
    hostname: anonymizer
    container_name: anonymizer
    ports:
    - "8091:1972"
    - "8092:52773"
    restart: on-failure
    volumes:
    - type: bind
      source: ./src
      target: /src